# Generated by Django 5.1.6 on 2025-02-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt_app', '0002_transcription_delete_audiotranscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='transcription',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
